### PR TITLE
add a line of code :>

### LINKED ISSUE #1: add close session
should add `dg.Close()` in [main.go](https://github.com/natsukagami/amabot/blob/master/cmd/bot/main.go) after the bot has finished running?

### PR DESCRIPTION
**Pull request by duongoku**
Resolves #1: add close session

---
This change is [Reviewable](https://reviewable.io/reviews/natsukagami/amabot/2)

### CODE REVIEW

**Review by natsukagami — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/natsukagami/amabot/2)* status: all files reviewed, 1 unresolved discussion (waiting on @duongoku)

___
*[cmd/bot/main.go, line 35 at r1](https://reviewable.io/reviews/natsukagami/amabot/2#-M8adzp28X2lx5AwK7QP:-M8adzp37y3qIump0Lnf:brel8ul) ([raw file](https://github.com/natsukagami/amabot/blob/dd0e15b59467213c117936ebc14a5fb330a05405/cmd/bot/main.go#L35)):*
> ```Go
> 
> 	amabot.Loop(dg, stopListening)
> 	dg.Close()
> ```

Can you make Close a deferred call after Open?

**Comment by duongoku** [comment]
Done!

**Review by natsukagami — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/natsukagami/amabot/2)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by natsukagami** [comment]
:thankyou:

**Pull request merged**
